export * as auth from './auth'
export * as catalog  from './catalog'
export * as news from './news'
export * as product from './product'
export * as newsletter from './newsletter'
export * as feedback from './feedback'